VectorStore:
  persist_directory: "data/chroma_db"
  insertion_mode: incremental # 'incremental'| 'full' |'scoped_full'
  top_k: 10


LLM:
  source: ChatGoogleGenerativeAI
  source_config:
    model: gemini-2.5-flash-lite # gemini-2.0-flash
    temperature: 0.1
    streaming: false

EmbeddingModel:
  source: GoogleGenerativeAIEmbeddings
  source_config:
    model: models/gemini-embedding-001
    task_type: RETRIEVAL_DOCUMENT

RerankerModel: 
  source: CohereRerank
  source_config:
    model: rerank-multilingual-v3.0
    top_n: 3

Database:
  db_name: record_manager_cache.sql

RAG:
  llm: ${LLM}
  embedding_model: ${EmbeddingModel}
  reranker: ${RerankerModel}
  vector_store: ${VectorStore}
  database: ${Database}
  chunk_size: 500
  chunk_overlap: 50


